# NumPy

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [8]:
arr = np.array(([1,2,3] , [1,6,3]))
arr

array([[1, 2, 3],
       [1, 6, 3]])

In [10]:
arr = np.array(([1,2,3] , [1,6,3], [2,3,5]))
arr

array([[1, 2, 3],
       [1, 6, 3],
       [2, 3, 5]])

In [17]:
arr = np.array([1,2,3], ndmin=3)
print(arr.ndim)

print(arr[0][0][1])

3
2


In [25]:
arr = np.zeros((2,4))
arr1 = np.ones((2,2))
arr1

array([[1., 1.],
       [1., 1.]])

In [29]:
arr = np.random.rand(3,3)
arr

array([[0.15917231, 0.61118685, 0.42684033],
       [0.1610817 , 0.52912302, 0.42425973],
       [0.1673222 , 0.88282295, 0.79456371]])

In [30]:
arr1 = [1,2,3]
arr2 = [2,4,5]

arr = np.add(arr1, arr2)
#np.substract para resta
#np.multiply para multi
#np.divide para división


arr

array([3, 6, 8])

### Probabilidad

In [31]:
#Tenemos comandos de numpy
#mean, max, min, median

### Indexación

In [36]:
arr = np.random.rand(3,3)
print(arr)
print(arr[0,1])
print(arr[-1])

[[0.15857635 0.78561125 0.96107676]
 [0.19426273 0.86333765 0.98869515]
 [0.33193704 0.94451428 0.27497071]]
0.7856112516188417
[0.33193704 0.94451428 0.27497071]


### Slicing 

In [38]:
arr = [1,2,3,4,5,6,7]
print(arr[0:5])
print(arr[1:5:2])

[1, 2, 3, 4, 5]
[2, 4]
