# NumPy

### Introducción

In [108]:
import numpy as np

In [109]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [110]:
arr = np.array(([1,2,3] , [1,6,3]))
arr

array([[1, 2, 3],
       [1, 6, 3]])

In [111]:
arr = np.array(([1,2,3] , [1,6,3], [2,3,5]))
arr

array([[1, 2, 3],
       [1, 6, 3],
       [2, 3, 5]])

In [112]:
arr = np.array([1,2,3], ndmin=3)
print(arr.ndim)

print(arr[0][0][1])

3
2


In [113]:
arr = np.zeros((2,4))
arr1 = np.ones((2,2))
arr1

array([[1., 1.],
       [1., 1.]])

In [114]:
arr = np.random.rand(3,3)
arr

array([[0.41820997, 0.03132061, 0.90013387],
       [0.76647787, 0.14965882, 0.75672675],
       [0.72583258, 0.55604728, 0.57051947]])

In [115]:
arr1 = [1,2,3]
arr2 = [2,4,5]

arr = np.add(arr1, arr2)
#np.substract para resta
#np.multiply para multi
#np.divide para división


arr

array([3, 6, 8])

### Probabilidad

In [116]:
#Tenemos comandos de numpy
#mean, max, min, median

### Indexación

In [117]:
arr = np.random.rand(3,3)
print(arr)
print(arr[0,1])
print(arr[-1])

[[0.80354484 0.89265592 0.57689613]
 [0.72716538 0.21425312 0.58281466]
 [0.71494935 0.37762395 0.68104594]]
0.89265591950127
[0.71494935 0.37762395 0.68104594]


### Slicing 

In [118]:
arr = [1,2,3,4,5,6,7]
print(arr[0:5])
print(arr[1:5:2])

[1, 2, 3, 4, 5]
[2, 4]


### Tipos de datos

In [119]:
arr = np.array([1,2,3])
arr1 = np.array(["a" , "b"])

print(arr.dtype)
print(arr1.dtype)

int32
<U1


In [120]:
arr = np.array([1,2,3] , dtype='i')
print(arr)
print(arr.dtype)

# 'i' integer
# 'b' boolenao
# 'f' flotante
# 'M' datatime
# 'O' objeto
# 'S' string

[1 2 3]
int32


In [121]:
arr = np.array([1.1, 1.6, 3.2])
print(arr)

nuevo_arr = arr.astype('i')
print(nuevo_arr)


[1.1 1.6 3.2]
[1 1 3]


### Copy vs View

In [122]:
arr = np.array([1,2,3])

x = arr.copy()
y = arr.view()

print('arreglo' ,arr)
print('x', x)
print('y', y)

arr[0] = 0

print('arreglo' ,arr)
print('x', x)
print('y', y)

arreglo [1 2 3]
x [1 2 3]
y [1 2 3]
arreglo [0 2 3]
x [1 2 3]
y [0 2 3]


### Concatenar

In [123]:
arr1 = np.array([1,2])

arr2 = np.array([2,5])

arr3 = np.concatenate((arr1, arr2))
arr3

array([1, 2, 2, 5])

### Búsqueda

In [124]:
arr = np.array([1,1,2,3,5,5,6,5,2,1])
x = np.where(arr == 5)

print(x)

(array([4, 5, 7], dtype=int64),)


### Code

In [125]:
arr = np.array([2,5,7,3,4])

x = np.sort(arr)

print(arr)
print(x)

[2 5 7 3 4]
[2 3 4 5 7]


# Pandas

### Introducción

In [126]:
import pandas as pd

In [127]:
a = np.array([10,2,45])
series = pd.Series(a)

print(series)
print(series[0])

0    10
1     2
2    45
dtype: int32
10


In [128]:
series = pd.Series(a, index = ['x', "y", "z"])
series

x    10
y     2
z    45
dtype: int32

In [129]:
pasos = {
    'Lunes' : 440,
    'Martes' :620,
    'Miércoles' : 1000
}

print(pasos)

series = pd.Series(pasos)
print(series)

{'Lunes': 440, 'Martes': 620, 'Miércoles': 1000}
Lunes         440
Martes        620
Miércoles    1000
dtype: int64


In [130]:
series = pd.Series(pasos, index = ['Lunes', 'Miércoles'])

print(series)

Lunes         440
Miércoles    1000
dtype: int64


### Dataframe

In [131]:
di = {
    'operador' :['John', 'Juan' , 'Manuel'],
    'N° de reloj' : [101, 202, 303]
}

df = pd.DataFrame(di)

print(df)

  operador  N° de reloj
0     John          101
1     Juan          202
2   Manuel          303


In [132]:
df[df['N° de reloj'] > 200 ]

operador  N° de reloj
1     Juan          202
2   Manuel          303

In [133]:
df['asistencia'] = [True, False, True]


In [134]:
df['asistencia']
df

operador  N° de reloj  asistencia
0     John          101        True
1     Juan          202       False
2   Manuel          303        True

In [135]:
print(df.loc[0])

operador       John
N° de reloj     101
asistencia     True
Name: 0, dtype: object


In [136]:
print(df.loc[1:2])


  operador  N° de reloj  asistencia
1     Juan          202       False
2   Manuel          303        True


In [137]:
df = pd.DataFrame(di, index = ["a", "b" , "c"])
df

operador  N° de reloj
a     John          101
b     Juan          202
c   Manuel          303

### Vistas

In [138]:
df = pd.read_csv("C:\Julio\Python_Intermedio\dataset\Perfil de estudiante.csv")

In [139]:
df.head()

Marca temporal   1.- ¿De dónde eres?  \
0  2023/06/27 7:42:12 p. m. GMT-6            Cd. Juárez   
1  2023/06/27 7:42:28 p. m. GMT-6  chihuahua, chihuahua   
2  2023/06/27 7:42:44 p. m. GMT-6   Chihuahua Chihuahua   
3  2023/06/27 7:42:52 p. m. GMT-6   Chihuahua Chihuahua   
4  2023/06/27 7:42:56 p. m. GMT-6      Chihuahua, Chih.   

  2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
0             Entre 21 y 24             Sí             No   
1             Entre 21 y 24             Sí             Sí   
2             Entre 18 y 20             Sí             Sí   
3             Entre 21 y 24             Sí             Sí   
4                 Más de 30             No             Sí   

  5.- ¿Cuál es tu nivel de conocimiento en Python?  \
0                                           Básico   
1                                           Básico   
2                                           Básico   
3                                           Básico   
4                                           Básico   

  6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
0                             Manejar bases de datos           
1                                    machine lerning           
2      Automatización y creación de apps/páginas web           
3                                  Análisis de datos           
4                              Conocer más librerias           

  7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
0                                                 No                   
1                                                 Sí                   
2                                                 No                   
3                                                 Sí                   
4                                                 Sí                   

  8.- ¿Cuál es tu canción favorita?  
0                          The Wolf  
1                   eternity, anyma  
2    Cornerstone- Arctic Monkeys :)  
3                   Sea Gets Hotter  
4        Love Me More, de Sam Smith

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 9 columns):
 #   Column                                                              Non-Null Count  Dtype 
---  ------                                                              --------------  ----- 
 0   Marca temporal                                                      43 non-null     object
 1   1.- ¿De dónde eres?                                                 43 non-null     object
 2   2.- ¿Cuántos años tienes?                                           43 non-null     object
 3   3.- ¿Estudias?                                                      43 non-null     object
 4   4.- ¿Trabajas?                                                      43 non-null     object
 5   5.- ¿Cuál es tu nivel de conocimiento en Python?                    43 non-null     object
 6   6.- ¿Qué tema relacionado con Python te gustaría aprender?          43 non-null     object
 7   7.- ¿Has participado en algún

In [141]:
df.tail()

Marca temporal                1.- ¿De dónde eres?  \
38  2023/06/27 10:02:11 p. m. GMT-6                Ciudad Juarez, Chih   
39  2023/06/27 10:31:28 p. m. GMT-6                          cd juarez   
40  2023/06/28 10:12:04 p. m. GMT-6                          Chihuahua   
41   2023/06/29 2:00:51 a. m. GMT-6  Vivo en Ciudad Juárez. Soy cubana   
42   2023/07/03 1:55:24 p. m. GMT-6                      Ciudad Juarez   

   2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
38             Entre 21 y 24             No             Sí   
39             Entre 21 y 24             Sí             Sí   
40             Entre 21 y 24             No             Sí   
41                 Más de 30             Sí             No   
42                 Más de 30             No             Sí   

   5.- ¿Cuál es tu nivel de conocimiento en Python?  \
38                                           Básico   
39                                           Básico   
40                                           Básico   
41                                       Intermedio   
42                                       Intermedio   

   6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
38                                  Analisis de datos           
39                                           punteros           
40                   Machine Learning y Deep Learning           
41  Cómo escribir un código de forma profesional, ...           
42                                     Automatizacion           

   7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
38                                                 Sí                   
39                                                 Sí                   
40                                                 Sí                   
41                                                 No                   
42                                                 No                   

                    8.- ¿Cuál es tu canción favorita?  
38                       https://youtu.be/BGVUiMskx_U  
39                             porter guiame quetzal   
40                                            Runaway  
41  Hay varias, pero últimamente escucho mucho "Cu...  
42                              David Bowie - Heroes

### CSV

In [142]:
df = pd.read_csv('C:\Julio\Python_Intermedio\dataset\Perfil de estudiante.csv')

print(df.to_string())

                     Marca temporal                        1.- ¿De dónde eres? 2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas? 5.- ¿Cuál es tu nivel de conocimiento en Python?                                           6.- ¿Qué tema relacionado con Python te gustaría aprender? 7.- ¿Has participado en algún curso anteriormente en el IA Center?                             8.- ¿Cuál es tu canción favorita?
0    2023/06/27 7:42:12 p. m. GMT-6                                 Cd. Juárez             Entre 21 y 24             Sí             No                                           Básico                                                                               Manejar bases de datos                                                                 No                                                      The Wolf
1    2023/06/27 7:42:28 p. m. GMT-6                       chihuahua, chihuahua             Entre 21 y 24             Sí             Sí                                      

### JSON

In [143]:
df = pd.read_json('C:\Julio\Python_Intermedio\dataset\dataset.json')
print(df.to_string())


                                                 personas
0      {'nombre': 'Juan', 'edad': 25, 'ciudad': 'Madrid'}
1  {'nombre': 'María', 'edad': 30, 'ciudad': 'Barcelona'}
2   {'nombre': 'Pedro', 'edad': 35, 'ciudad': 'Valencia'}


### Limpieza de datos

In [144]:
data = {
    'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis'],
    'Edad': [25, 32, None, 42, 28],
    'Fecha': ['31/01/2020', '31/01/2020', None, '31/01/2020', '01/31/2020'],
    'Género': ['M', 'F', None, 'F', 'M'],
    'Ciudad': ['Madrid', None, 'Madrid', 'Valencia', 'Barcelona'],
    'Altura': [175, 163, 180, 158, 170],
    'Peso': [70, None, 80, 60, 75],
    'Ingresos': [50000, 60000, 40000, None, 55000]
}

In [162]:
df = pd.DataFrame(data)

print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [146]:
df_vacios = df.dropna() #Esto nos genera una copia

print(df_vacios.to_string())

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [147]:
df.dropna(inplace=True) #Esto modifica el data frame original

print(df.to_string())

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [151]:
df.fillna('vacio', inplace=True)

print(df)

  Nombre   Edad       Fecha Género     Ciudad  Altura   Peso Ingresos
0   Juan   25.0  31/01/2020      M     Madrid     175   70.0  50000.0
1  María   32.0  31/01/2020      F      vacio     163  vacio  60000.0
2  Pedro  vacio       vacio  vacio     Madrid     180   80.0  40000.0
3    Ana   42.0  31/01/2020      F   Valencia     158   60.0    vacio
4   Luis   28.0  01/31/2020      M  Barcelona     170   75.0  55000.0


In [160]:
df['Ingresos'].fillna(0, inplace=True) #Esto cambia el valor de los nulosde ingresos

print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       0.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [161]:
media = df['Ingresos'].mean()
print(media)

41000.0


In [163]:
df['Ingresos'].fillna(media, inplace = True)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0   41000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [170]:
promedio = df['Peso'].mean()
print(promedio)

df['Peso'].fillna(promedio, inplace=True)
df 

71.25


Nombre  Edad       Fecha Género     Ciudad  Altura   Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.00   50000.0
1  María  32.0  31/01/2020      F       None     163  71.25   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.00   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.00   41000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.00   55000.0

In [174]:
df.loc[1, 'Peso'] = 74

df

Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163  74.0   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0   41000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0

In [177]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [185]:
df.drop_duplicates(inplace = True)
df

Nombre  Edad       Fecha Género    Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M    Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F      None     163   NaN   60000.0
2  Pedro   NaN        None   None    Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F  Valencia     158  60.0       NaN

In [186]:
#df.corr() para buscar relaciones entre los datos 

## Ejercicio

#### Limpiar el siguiente dataset 
 data = {
    'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis'],
    'Edad': [25, 32, None, 42, 28],
    'Fecha': ['31/01/2020', '31/01/2020', None, '31/01/2020', '01/31/2020'],
    'Género': ['M', 'F', None, 'F', 'M'],
    'Ciudad': ['Madrid', None, 'Madrid', 'Valencia', 'Barcelona'],
    'Altura': [175, 163, 180, 158, 170],
    'Peso': [70, None, 80, 60, 75],
    'Ingresos': [50000, 60000, 40000, None, 55000]
 }

In [192]:
#Importar el dataset y volverlo un dataframe

data = {
    'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis'],
    'Edad': [25, 32, None, 42, 28],
    'Fecha': ['31/01/2020', '31/01/2020', None, '31/01/2020', '01/31/2020'],
    'Género': ['M', 'F', None, 'F', 'M'],
    'Ciudad': ['Madrid', None, 'Madrid', 'Valencia', 'Barcelona'],
    'Altura': [175, 163, 180, 158, 170],
    'Peso': [70, None, 80, 60, 75],
    'Ingresos': [50000, 60000, 40000, None, 55000]
}

dataf = pd.DataFrame(data)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [193]:
df = dataf
promedio = df['Edad'].mean()
df['Edad'].fillna(promedio, inplace = True)

promedio2 = df['Peso'].mean()
df['Peso'].fillna(promedio2, inplace = True)

promedio3 = df['Ingresos'].mean()
df['Edad'].fillna(promedio3, inplace = True)

print(df)

  Nombre   Edad       Fecha Género     Ciudad  Altura   Peso  Ingresos
0   Juan  25.00  31/01/2020      M     Madrid     175  70.00   50000.0
1  María  32.00  31/01/2020      F       None     163  71.25   60000.0
2  Pedro  31.75        None   None     Madrid     180  80.00   40000.0
3    Ana  42.00  31/01/2020      F   Valencia     158  60.00       NaN
4   Luis  28.00  01/31/2020      M  Barcelona     170  75.00   55000.0


In [197]:
df.fillna('SR', inplace=True)

print(df)

  Nombre   Edad       Fecha Género     Ciudad  Altura   Peso Ingresos
0   Juan  25.00  31/01/2020      M     Madrid     175  70.00  50000.0
1  María  32.00  31/01/2020      F         SR     163  71.25  60000.0
2  Pedro  31.75          SR     SR     Madrid     180  80.00  40000.0
3    Ana  42.00  31/01/2020      F   Valencia     158  60.00       SR
4   Luis  28.00  01/31/2020      M  Barcelona     170  75.00  55000.0
