# NumPy

### Introducción

In [6]:
import numpy as np

In [4]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [8]:
arr = np.array(([1,2,3] , [1,6,3]))
arr

array([[1, 2, 3],
       [1, 6, 3]])

In [10]:
arr = np.array(([1,2,3] , [1,6,3], [2,3,5]))
arr

array([[1, 2, 3],
       [1, 6, 3],
       [2, 3, 5]])

In [17]:
arr = np.array([1,2,3], ndmin=3)
print(arr.ndim)

print(arr[0][0][1])

3
2


In [25]:
arr = np.zeros((2,4))
arr1 = np.ones((2,2))
arr1

array([[1., 1.],
       [1., 1.]])

In [29]:
arr = np.random.rand(3,3)
arr

array([[0.15917231, 0.61118685, 0.42684033],
       [0.1610817 , 0.52912302, 0.42425973],
       [0.1673222 , 0.88282295, 0.79456371]])

In [30]:
arr1 = [1,2,3]
arr2 = [2,4,5]

arr = np.add(arr1, arr2)
#np.substract para resta
#np.multiply para multi
#np.divide para división


arr

array([3, 6, 8])

### Probabilidad

In [31]:
#Tenemos comandos de numpy
#mean, max, min, median

### Indexación

In [36]:
arr = np.random.rand(3,3)
print(arr)
print(arr[0,1])
print(arr[-1])

[[0.15857635 0.78561125 0.96107676]
 [0.19426273 0.86333765 0.98869515]
 [0.33193704 0.94451428 0.27497071]]
0.7856112516188417
[0.33193704 0.94451428 0.27497071]


### Slicing 

In [38]:
arr = [1,2,3,4,5,6,7]
print(arr[0:5])
print(arr[1:5:2])

[1, 2, 3, 4, 5]
[2, 4]


### Tipos de datos

In [9]:
arr = np.array([1,2,3])
arr1 = np.array(["a" , "b"])

print(arr.dtype)
print(arr1.dtype)

int32
<U1


In [22]:
arr = np.array([1,2,3] , dtype='i')
print(arr)
print(arr.dtype)

# 'i' integer
# 'b' boolenao
# 'f' flotante
# 'M' datatime
# 'O' objeto
# 'S' string

[1 2 3]
int32


In [27]:
arr = np.array([1.1, 1.6, 3.2])
print(arr)

nuevo_arr = arr.astype('i')
print(nuevo_arr)


[1.1 1.6 3.2]
[1 1 3]


### Copy vs View

In [31]:
arr = np.array([1,2,3])

x = arr.copy()
y = arr.view()

print('arreglo' ,arr)
print('x', x)
print('y', y)

arr[0] = 0

print('arreglo' ,arr)
print('x', x)
print('y', y)

arreglo [1 2 3]
x [1 2 3]
y [1 2 3]
arreglo [0 2 3]
x [1 2 3]
y [0 2 3]


### Concatenar

In [34]:
arr1 = np.array([1,2])

arr2 = np.array([2,5])

arr3 = np.concatenate((arr1, arr2))
arr3

array([1, 2, 2, 5])

### Búsqueda

In [35]:
arr = np.array([1,1,2,3,5,5,6,5,2,1])
x = np.where(arr == 5)

print(x)

(array([4, 5, 7], dtype=int64),)


### Code

In [36]:
arr = np.array([2,5,7,3,4])

x = np.sort(arr)

print(arr)
print(x)

[2 5 7 3 4]
[2 3 4 5 7]


# Pandas

### Introducción

In [37]:
import pandas as pd

In [41]:
a = np.array([10,2,45])
series = pd.Series(a)

print(series)
print(series[0])

0    10
1     2
2    45
dtype: int32
10


In [44]:
series = pd.Series(a, index = ['x', "y", "z"])
series

x    10
y     2
z    45
dtype: int32

In [49]:
pasos = {
    'Lunes' : 440,
    'Martes' :620,
    'Miércoles' : 1000
}

print(pasos)

series = pd.Series(pasos)
print(series)

{'Lunes': 440, 'Martes': 620, 'Miércoles': 1000}
Lunes         440
Martes        620
Miércoles    1000
dtype: int64


In [50]:
series = pd.Series(pasos, index = ['Lunes', 'Miércoles'])

print(series)

Lunes         440
Miércoles    1000
dtype: int64


### Dataframe

In [54]:
di = {
    'operador' :['John', 'Juan' , 'Manuel'],
    'N° de reloj' : [10, 20, 30]
}

serie_d = pd.Series(di)

print(serie_d)

operador       [John, Juan, Manuel]
N° de reloj            [10, 20, 30]
dtype: object
